import Image from "next/image"
import {
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpCircleIcon,
  ArrowUpDown,
  AtSignIcon,
  BadgeCheck,
  BarChart,
  Bell,
  BookIcon,
  BookImageIcon,
  BookOpenText,
  Brain,
  Calendar,
  CalendarSearchIcon,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRightIcon,
  ChevronsUpDown,
  Circle,
  Clock,
  CoinsIcon,
  CopyIcon,
  CreditCard,
  DatabaseZapIcon,
  DollarSign,
  File,
  FileText,
  Folder,
  GithubIcon,
  GlobeIcon,
  HelpCircle,
  HomeIcon,
  HospitalIcon,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyIcon,
  Laptop,
  LayoutDashboardIcon,
  LineChartIcon,
  ListIcon,
  Loader2,
  LockIcon,
  LogIn,
  LogOut,
  LucideIcon,
  MailIcon,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  PuzzleIcon,
  RefreshCw,
  SaveIcon,
  Search,
  Settings,
  Shield,
  Sparkles,
  SquareTerminal,
  Stethoscope,
  SunMedium,
  ToggleRightIcon,
  Trash,
  TrendingDown,
  TrendingUp,
  UserCircleIcon,
  UserCogIcon,
  UserPlus,
  Users,
  X,
  ZapIcon,
} from "lucide-react"

import { cn } from "@/lib/utils"

export type Icon = LucideIcon

function LogoIcon({ className }: { className?: string }) {
  return <span className={cn(className)}>🔐</span>
}

function LastPassIcon({ className }: { className?: string }) {
  return (
    <Image
      src="/logos/lastpass.svg"
      alt="LastPass"
      width={48}
      height={48}
      className={cn(className, "inline-block object-contain align-middle")}
    />
  )
}

function HashiCorpIcon({ className }: { className?: string }) {
  return (
    <Image
      src="/logos/hashicorp.svg"
      alt="HashiCorp"
      width={48}
      height={48}
      className={cn(className, "inline-block object-contain align-middle")}
    />
  )
}

export const Icons = {
  logo: LogoIcon,
  logoLucide: ChevronsRightIcon,
  close: X,
  up: ArrowUp,
  down: ArrowDown,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  check: Check,
  orderbook: BookOpenText,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  lock: LockIcon,
  puzzle: PuzzleIcon,
  globe: GlobeIcon,
  databaseZap: DatabaseZapIcon,
  blog: BookImageIcon,
  graph: LineChartIcon,
  zap: ZapIcon,
  copy: CopyIcon,
  toggleRight: ToggleRightIcon,
  creditCard: CreditCard,
  calendar: Calendar,
  barChart: BarChart,
  clock: Clock,
  brain: Brain,
  menu: Menu,
  document: BookIcon,
  folder: Folder,
  more: MoreHorizontal,
  badgeCheck: BadgeCheck,
  bell: Bell,
  logOut: LogOut,
  sparkles: Sparkles,
  studio: SquareTerminal,
  register: UserPlus,
  appointment: CalendarSearchIcon,
  coins: CoinsIcon,
  location: MapPin,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  dollarSign: DollarSign,
  users: Users,
  inbox: Inbox,
  arrowUpDown: ArrowUpDown,
  circle: Circle,
  helpCircle: HelpCircle,
  shield: Shield,
  therapist: Stethoscope,
  staff: Users,
  pending: Loader2,
  approved: Check,
  rejected: X,
  contacted: MailIcon,
  demoScheduled: CalendarSearchIcon,
  demoCompleted: Check,
  contractSigned: FileText,
  onboarding: UserCogIcon,
  joined: UserPlus,
  referred: UserPlus,
  purchased: CoinsIcon,
  converted: Check,
  churned: X,
  reactivated: RefreshCw,
  upgraded: ArrowUpCircleIcon,
  downgraded: ArrowDown,
  refunded: ArrowDown,
  cancelled: X,
  expired: Clock,
  trialed: Check,
  subscribed: Check,
  unsubscribed: X,
  suspended: X,
  resumed: Check,
  paused: Circle,
  lastpass: LastPassIcon,
  hashicorp: HashiCorpIcon,
  github: GithubIcon,
  home: HomeIcon,
  dashboard: LayoutDashboardIcon,
  key: KeyIcon,
  save: SaveIcon,
  info: Info,
  list: ListIcon,
  at: AtSignIcon,
  logIn: LogIn,
  chevronDown: ChevronDown,
  hospital: HospitalIcon,
}
